version: '3.7'

services:
  db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: development

  web:
    build: server
    image: weather-server
    command: web
    stdin_open: true
    tty: true
    volumes:
      - ./server:/opt/app:Z
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: postgresql://postgres:development@db:5432/weather_development
      RAILS_ENV: development
    depends_on:
      - db

  front:
    build: front
    image: weather-front
    stdin_open: true
    tty: true
    volumes:
      - ./front:/opt/app:Z
    ports:
      - "3000:3000"
    depends_on:
      - web
