version: '3.7'

services:
  db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: development

  web:
    build: server
    image: weather-server
    command: web
    stdin_open: true
    tty: true
    volumes:
      - ./server:/opt/app:Z
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: postgresql://postgres:development@db:5432/weather_development
      RAILS_ENV: development
      OPEN_WEATHER_MAP_APP_ID: ${OPEN_WEATHER_MAP_APP_ID}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    depends_on:
      - db

  test:
    build: server
    image: weather-server
    command: test
    stdin_open: true
    tty: true
    volumes:
      - ./server:/opt/app:Z
    environment:
      DATABASE_URL: postgresql://postgres:development@db:5432/weather_test
      RAILS_ENV: test
    depends_on:
      - db

  front:
    build: front
    image: weather-front
    stdin_open: true
    tty: true
    volumes:
      - ./front:/opt/app:Z
    ports:
      - "3000:3000"
    environment:
      OPEN_WEATHER_MAP_APP_ID: ${OPEN_WEATHER_MAP_APP_ID}
      REACT_APP_API_URI: ${REACT_APP_API_URI}
      REACT_APP_FACEBOOK_ID: ${REACT_APP_FACEBOOK_ID}
    depends_on:
      - web
