AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - db/**/*

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MixinUsage:
  Enabled: false
  Exclude:
    - bin/*
